### ISSUE TITLE
API setup instructions and failures

### ISSUE THREAD

**Issue by olivierobert** [nattaponaie/nimble-challenge#13]
While the README is quite complete, it lacks instructions on properly setting up the PostgreSQL database required for the API.

If one just builds the containers and run them with `docker-compose up` (this should be added to the README as well by the way) then this person would be greeted by this error:

![browser-error](https://user-images.githubusercontent.com/696529/63483311-2a137e00-c4c6-11e9-80ce-555afea07d5a.jpg)

Which is caused by:

![console-error](https://user-images.githubusercontent.com/696529/63483319-326bb900-c4c6-11e9-999b-9efd8d1c5875.jpg)

Therefore, either the README must mention that the database must be migrated with ` docker exec -ti toey_api_1 rake db:migrate` or you need to edit the container command to migrate the database in development (let's never do that in production ☠️).

Also, note that one of the migration has a small typo which makes all migration fail:

![toey___Volumes_Workspace__candidates-tests_toey__-_____docker-compose_yml](https://user-images.githubusercontent.com/696529/63483430-8a0a2480-c4c6-11e9-95b0-0bc2ce92b667.jpg)

Caused by:

![toey___Volumes_Workspace__candidates-tests_toey__-_____api_db_migrate_20190817070848_add_is_searched_to_keyword_rb](https://user-images.githubusercontent.com/696529/63483447-a017e500-c4c6-11e9-8b80-151c2117342a.jpg)

**Comment by tobyaie** [comment]
Thank you for your suggestion. 

According to latest pull request, I already fixed the issues you said above.
This includes error handling when there is an error from API as well.

Moreover, I have added `rake db:migrate` command to docker-compose. Since the docker-compose will be used only in development so it's fine :)
